const pokemonData = [
  // --- ORDER 1: STARTERS & GRAND HALL ---
  { "name": "Bulbasaur", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Charmander", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Squirtle", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Chikorita", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Cyndaquil", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Totodile", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Treecko", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Torchic", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Mudkip", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Turtwig", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Chimchar", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Piplup", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Snivy", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Tepig", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Oshawott", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Chespin", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Fennekin", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Froakie", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Rowlet", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Litten", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Popplio", "locations": ["Grand Hall (Event) [Starter]"], "order": 1 },
  { "name": "Vulpix", "locations": ["Grand Hall (Event) [vulpixpls password]", "Jasper Ward (Event) [Mystery Egg]"], "order": 1 },
  { "name": "Eevee", "locations": ["Grand Hall (Event) [eeveepls password]"], "order": 1 },

  // --- ORDER 2-5: PERIDOT & OPAL WARD (Early Game) ---
  { "name": "Caterpie", "locations": ["Lower Peridot Ward (Land)"], "order": 2 },
  { "name": "Weedle", "locations": ["Lower Peridot Ward (Land)"], "order": 2 },
  { "name": "Pidgey", "locations": ["Jasper Ward (Cave)", "Opal Ward (Land)"], "order": 3 },
  { "name": "Rattata", "locations": ["Opal Ward (Land)"], "order": 3 },
  { "name": "Ekans", "locations": ["Opal Ward (Land)", "Beryl Ward (Land)"], "order": 3 },
  { "name": "Spearow", "locations": ["Opal Ward (Headbutt)", "Beryl Ward (Cave)"], "order": 3 },
  { "name": "Meowth", "locations": ["Opal Ward (Land)", "Obsidia Slums (Cave)"], "order": 3 },
  { "name": "Patrat", "locations": ["Opal Ward (Land)"], "order": 3 },
  { "name": "Zigzagoon", "locations": ["Opal Ward (Event) [50% Chance]"], "order": 3 },
  { "name": "Pachirisu", "locations": ["Opal Ward (Event) [50% Chance]"], "order": 3 },
  { "name": "Bidoof", "locations": ["Opal Ward (Land)"], "order": 3 },
  { "name": "Hoothoot", "locations": ["Opal Ward (Land, Night)", "Obsidia Ward (Land, Night)"], "order": 3 },
  { "name": "Spinarak", "locations": ["Opal Ward (Land, Night)", "Lower Peridot Ward (Land, Night)"], "order": 3 },
  { "name": "Pineco", "locations": ["Opal Ward (Headbutt)"], "order": 3 },
  { "name": "Combee", "locations": ["Opal Ward (Headbutt)"], "order": 3 },
  { "name": "Burmy", "locations": ["Lower Peridot Ward (Headbutt)"], "order": 4 },
  { "name": "Cherubi", "locations": ["Lower Peridot Ward (Land, Morning, Day)"], "order": 4 },
  { "name": "Ledyba", "locations": ["Lower Peridot Ward (Land, Morning)"], "order": 4 },
  { "name": "Sunkern", "locations": ["Lower Peridot Ward (Land)"], "order": 4 },
  { "name": "Wurmple", "locations": ["Lower Peridot Ward (Land)"], "order": 4 },
  { "name": "Kricketot", "locations": ["Lower Peridot Ward (Event)"], "order": 4 },
  { "name": "Whismur", "locations": ["Lower Peridot Ward (Event) [Pokesnax]"], "order": 4 },
  { "name": "Gulpin", "locations": ["Lower Peridot Ward (Event) [Pokesnax]"], "order": 4 },
  { "name": "Minccino", "locations": ["Lower Peridot Ward (Event) [25%, Pokesnax]"], "order": 4 },
  { "name": "Espurr", "locations": ["Lower Peridot Ward (Event) [25%, Pokesnax]"], "order": 4 },
  { "name": "Swinub", "locations": ["Lower Peridot Ward (Event) [Pokesnax, MonoIce Password]"], "order": 4 },
  { "name": "Dwebble", "locations": ["Lower Peridot Ward (Event) [monorock password]"], "order": 4 },
  { "name": "Aron", "locations": ["Lower Peridot Ward (Event) [Pokesnax, MonoRock password]"], "order": 4 },
  { "name": "Teddiursa", "locations": ["Lower Peridot Ward (Event) [Day]"], "order": 4 },
  { "name": "Stunky", "locations": ["Lower Peridot Ward (Land, Night)"], "order": 4 },
  { "name": "Zangoose", "locations": ["Lower Peridot Ward (Event, Night) [Weekday]"], "order": 4 },
  { "name": "Seaking", "locations": ["Lower Peridot Ward (Good Rod)"], "order": 4 },
  { "name": "Finneon", "locations": ["Lower Peridot Ward (Good Rod)"], "order": 4 },
  { "name": "Goldeen", "locations": ["Lower Peridot Ward (Good Rod)"], "order": 4 },
  { "name": "Grimer", "locations": ["Lower Peridot Ward (Old Rod)"], "order": 4 },
  { "name": "Muk", "locations": ["Lower Peridot Ward (Good Rod)"], "order": 4 },
  { "name": "Skrelp", "locations": ["Lower Peridot Ward (Good Rod)"], "order": 4 },
  { "name": "Tentacool", "locations": ["Lower Peridot Ward (Good Rod) [Poisoned lake.]"], "order": 4 },
  { "name": "Numel", "locations": ["Lower Peridot Ward (Event) [Pokesnax, Raining]"], "order": 4 },
  { "name": "Blitzle", "locations": ["Lower Peridot Ward (Event) [Thunderstorm]"], "order": 4 },
  { "name": "Poochyena", "locations": ["Obsidia Alleyway (Cave)"], "order": 5 },
  { "name": "Tynamo", "locations": ["Lower Peridot Alley (Event) [Thunderstorm]"], "order": 5 },
  { "name": "Munna", "locations": ["Peridot Ward (Event) [Trade Bibarel]"], "order": 6 },
  { "name": "Igglybuff", "locations": ["Peridot Ward (Event) [Abandoned Building Quest]"], "order": 6 },
  { "name": "Budew", "locations": ["Peridot Ward (Event) [Rose Incense]"], "order": 6 },
  { "name": "Surskit", "locations": ["Peridot Ward (Event) [Raining, Fountain]"], "order": 6 },
  { "name": "Snubbull", "locations": ["Peridot Ward (Event) [50%]"], "order": 6 },
  { "name": "Stufful", "locations": ["Peridot Ward (Event) [50%]"], "order": 6 },
  { "name": "Grubbin", "locations": ["Peridot Ward (Event, Night) [50%]"], "order": 6 },
  { "name": "Joltik", "locations": ["Peridot Ward (Event, Night) [50%]"], "order": 6 },
  { "name": "Drifloon", "locations": ["Peridot Ward (Event, Night) [Monoghost Only]"], "order": 6 },
  { "name": "Purrloin", "locations": ["North Peridot Alley (Cave)"], "order": 7 },
  { "name": "Geodude", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Graveler", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Drapion", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Diglett", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Dugtrio", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Sandshrew", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Sandslash", "locations": ["Grand Stairway (Cave)"], "order": 8 },
  { "name": "Unown", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Woobat", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Swoobat", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Noibat", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Mawile", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Klink", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Roggenrola", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Machop", "locations": ["Underground Railnet (Cave)"], "order": 8 },
  { "name": "Makuhita", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Hariyama", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Mankey", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Scraggy", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Scrafty", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Bunnelby", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Trubbish", "locations": ["Obsidia Slums (Cave)"], "order": 9 },
  { "name": "Yamask", "locations": ["Obsidia Slums (Event) [Box]"], "order": 9 },
  { "name": "Pancham", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Lillipup", "locations": ["Obsidia Slums (Land)"], "order": 9 },
  { "name": "Shinx", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Nidorina", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Nidorino", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Golett", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Clauncher", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Bergmite", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Mareanie", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Pyukumuku", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Slugma", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Helioptile", "locations": ["Obsidia Slums (Event) [Arcade]"], "order": 9 },
  { "name": "Sentret", "locations": ["Obsidia Park (Land, Morning, Day)"], "order": 10 },
  { "name": "Oddish", "locations": ["Obsidia Park (Land)"], "order": 10 },
  { "name": "Bonsly", "locations": ["Obsidia Park (Land, Morning, Day)"], "order": 10 },
  { "name": "Slakoth", "locations": ["Obsidia Park (Headbutt)"], "order": 10 },
  { "name": "Fomantis", "locations": ["Obsidia Park (Land, Day)"], "order": 10 },
  { "name": "Petilil", "locations": ["Obsidia Ward (Event) [Trade Cottonee]"], "order": 10 },
  { "name": "Cottonee", "locations": ["Obsidia Ward (Event) [Trade Petilil]"], "order": 10 },
  { "name": "Minun", "locations": ["Obsidia Ward (Event) [Jump Puzzle]"], "order": 10 },
  { "name": "Plusle", "locations": ["Obsidia Ward (Event) [Jump Puzzle]"], "order": 10 },
  { "name": "Castform", "locations": ["Obsidia Ward (Event) [Trade Furret]"], "order": 10 },
  { "name": "Bounsweet", "locations": ["Obsidia Ward (Event) [Trade Spinda]"], "order": 10 },
  { "name": "Luvdisc", "locations": ["Coral Ward (Old Rod)"], "order": 11 },
  { "name": "Corsola", "locations": ["Coral Ward (Land, Morning, Day)"], "order": 11 },
  { "name": "Horsea", "locations": ["Coral Ward (Good Rod)"], "order": 11 },
  { "name": "Shellder", "locations": ["Coral Ward (Good Rod)"], "order": 11 },
  { "name": "Wailmer", "locations": ["Coral Ward (Good Rod)"], "order": 11 },
  { "name": "Skrelp", "locations": ["Coral Ward (Good Rod)"], "order": 11 },
  { "name": "Mareanie", "locations": ["Coral Ward (Good Rod)"], "order": 11 },
  { "name": "Lotad", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Lombre", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Wingull", "locations": ["Coral Ward (Land, Morning, Day)"], "order": 11 },
  { "name": "Psyduck", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Wooper", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Quagsire", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Palpitoad", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Seismitoad", "locations": ["Coral Ward (Land)"], "order": 11 },
  { "name": "Hoppip", "locations": ["Coral Ward (Event) [Windy]"], "order": 11 },
  { "name": "Happiny", "locations": ["Coral Ward (Event) [Daycare Couple]"], "order": 11 },
  { "name": "Wimpod", "locations": ["Coral Ward (Event)"], "order": 11 },
  { "name": "Gothita", "locations": ["Beryl Library (Event) [Cleaning]"], "order": 13 },
  { "name": "Koffing", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Nuzleaf", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Shiftry", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Stantler", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Girafarig", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Ursaring", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Masquerain", "locations": ["Beryl Ward (Land)"], "order": 13 },
  { "name": "Seedot", "locations": ["Beryl Ward (Event) [Bulletproof Vest]"], "order": 13 },
  { "name": "Duskull", "locations": ["Beryl Ward (Land, Night)"], "order": 13 },
  { "name": "Shuppet", "locations": ["Beryl Cemetery (Event) [Pumpkin]"], "order": 13 },
  { "name": "Phantump", "locations": ["Beryl Cemetery (Land, Night)"], "order": 13 },
  { "name": "Pumpkaboo", "locations": ["Beryl Cemetery (Land, Night)"], "order": 13 },
  { "name": "Gastly", "locations": ["Beryl Cemetery (Land, Night)"], "order": 13 },
  { "name": "Haunter", "locations": ["Beryl Cemetery (Land, Night)"], "order": 13 },
  { "name": "Litwick", "locations": ["Beryl Ward (Event) [Soul Candle]"], "order": 13 },
  { "name": "Spritzee", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Swirlix", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Mareep", "locations": ["Jasper Ward (Land, Morning, Day)"], "order": 14 },
  { "name": "Flaaffy", "locations": ["Jasper Ward (Land, Day)"], "order": 14 },
  { "name": "Cottenee", "locations": ["Jasper Ward (Land, Morning, Day)"], "order": 14 },
  { "name": "Sewaddle", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Phanpy", "locations": ["Beryl Ward (Event) [Pickup]"], "order": 14 },
  { "name": "Emolga", "locations": ["Jasper Ward (Event) [Windy day]"], "order": 14 },
  { "name": "Fletchling", "locations": ["Jasper Ward (Land, Day)"], "order": 14 },
  { "name": "Scatterbug", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Spewpa", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Vivillon", "locations": ["Jasper Ward (Land)"], "order": 14 },
  { "name": "Pikipek", "locations": ["Jasper Ward (Land, Morning, Day)"], "order": 14 },
  { "name": "Trumbeak", "locations": ["Jasper Ward (Land, Morning, Day)"], "order": 14 },
  { "name": "Togepi", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Elekid", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Azurill", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Staryu", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Riolu", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Sneasel", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Shroomish", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Larvesta", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Axew", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Dratini", "locations": ["Jasper Ward (Event) [Mystery Egg]"], "order": 14 },
  { "name": "Tangela", "locations": ["Jasper Ward (Event) [Use Pokesnax]"], "order": 14 },
  { "name": "Murkrow", "locations": ["Lapis Ward (Event) [Aqua Gang]"], "order": 14 },
  { "name": "Carvanha", "locations": ["Lapis Alleyway (Event) [Aqua Gang]"], "order": 14 },
  { "name": "Ponyta", "locations": ["Lapis Ward (Event) [Magma Gang]"], "order": 14 },
  { "name": "Houndour", "locations": ["Lapis Ward (Event) [Magma Gang]"], "order": 14 },
  { "name": "Buizel", "locations": ["Lapis Ward (Event) [Magma Gang]"], "order": 14 },
  { "name": "Darumaka", "locations": ["Lapis Ward (Event) [Magma Gang]"], "order": 14 },
  { "name": "Misdreavus", "locations": ["Byxbysion Wasteland (Event) [Ghost Girl]"], "order": 16 },
  { "name": "Solosis", "locations": ["Byxbysion Wasteland (Land, Day)"], "order": 16 },
  { "name": "Gothita", "locations": ["Byxbysion Wasteland (Land)"], "order": 16 },
  { "name": "Gothorita", "locations": ["Byxbysion Wasteland (Land)"], "order": 16 },
  { "name": "Garbodor", "locations": ["Byxbysion Wasteland (Land)"], "order": 16 },
  { "name": "Klink", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Klang", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Klinklang", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Magnemite", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Magneton", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Voltorb", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Electabuzz", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Pikachu", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Galvantula", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Pawniard", "locations": ["Yureyu Power Plant (Cave)"], "order": 17 },
  { "name": "Rotom", "locations": ["Yureyu Power Plant (Event)"], "order": 17 },
  { "name": "Shuckle", "locations": ["Pyrous Mountain (Rock Smash)"], "order": 18 },
  { "name": "Slugma", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Magcargo", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Torkoal", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Heatmor", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Turtonator", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Machoke", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Meditite", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Mienfoo", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Throh", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Sawk", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Tyrogue", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Litleo", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Salandit", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Camerupt", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Magmar", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Darumaka", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Magby", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Larvesta", "locations": ["Pyrous Mountain (Cave)"], "order": 18 },
  { "name": "Tropius", "locations": ["Rhodochrine Jungle (Land, Morning, Day)"], "order": 19 },
  { "name": "Carnivine", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Roselia", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Gloom", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Weepinbell", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Exeggcute", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Venomoth", "locations": ["Rhodochrine Jungle (Land, Night)"], "order": 19 },
  { "name": "Paras", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Natu", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Chatot", "locations": ["Rhodochrine Jungle (Headbutt)"], "order": 19 },
  { "name": "Aipom", "locations": ["Rhodochrine Jungle (Headbutt)"], "order": 19 },
  { "name": "Heracross", "locations": ["Rhodochrine Jungle (Headbutt)"], "order": 19 },
  { "name": "Pinsir", "locations": ["Rhodochrine Jungle (Headbutt)"], "order": 19 },
  { "name": "Pikachu", "locations": ["Rhodochrine Jungle (Event) [Pichu Doll]"], "order": 19 },
  { "name": "Oranguru", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Passimian", "locations": ["Rhodochrine Jungle (Land)"], "order": 19 },
  { "name": "Goomy", "locations": ["Gleamwood (Land)"], "order": 19 },
  { "name": "Sliggoo", "locations": ["Gleamwood (Land)"], "order": 19 },
  { "name": "Eevee", "locations": ["Chrysolia Forest (Event) [Lost in trees]"], "order": 20 },
  
  // --- ORDER 21-30: BYXBYSION & 7TH STREET (Mid Game) ---
  { "name": "Gastly", "locations": ["Byxbysion Wasteland (Night)"], "order": 21 },
  { "name": "Koffing", "locations": ["Byxbysion Wasteland (Land)"], "order": 21 },
  { "name": "Grimer", "locations": ["Byxbysion Wasteland (Land)"], "order": 21 },
  { "name": "Stunky", "locations": ["Byxbysion Wasteland (Land)"], "order": 21 },
  { "name": "Venipede", "locations": ["Byxbysion Wasteland (Land)"], "order": 21 },
  { "name": "Aron", "locations": ["Byxbysion Wasteland (Headbutt)"], "order": 21 },
  { "name": "Mudkip", "locations": ["Byxbysion Wasteland (Event) [Rain]"], "order": 21 },
  { "name": "Squirtle", "locations": ["Byxbysion Wasteland (Event) [Rain]"], "order": 21 },
  { "name": "Tepig", "locations": ["Pyrous Mountain (Event) [Strength Puzzle]"], "order": 22 },
  { "name": "Solrock", "locations": ["Grand Stairway (Cave B2F)"], "order": 23 },
  { "name": "Lunatone", "locations": ["Grand Stairway (Cave B2F)"], "order": 23 },
  { "name": "Clefairy", "locations": ["Agate Circus (Land)"], "order": 24 },
  { "name": "Spinda", "locations": ["Agate Circus (Land)"], "order": 24 },
  { "name": "Voltorb", "locations": ["Route 2 (Land)"], "order": 24 },
  { "name": "Foongus", "locations": ["Azurine Island (Land)"], "order": 25 },
  { "name": "Amoonguss", "locations": ["Azurine Island (Land)"], "order": 25 },
  { "name": "Shelmet", "locations": ["Azurine Island (Land)"], "order": 25 },
  { "name": "Karrablast", "locations": ["Azurine Island (Land)"], "order": 25 },
  { "name": "Inkay", "locations": ["Byxbysion Wasteland (Headbutt)"], "order": 25 },
  { "name": "Porygon", "locations": ["Glitch World (Land)"], "order": 26 },
  { "name": "Abra", "locations": ["7th Street (Purchase)"], "order": 27 },
  { "name": "Jigglypuff", "locations": ["7th Street (Purchase)"], "order": 27 },
  { "name": "Lickitung", "locations": ["7th Street (Purchase)"], "order": 27 },
  { "name": "Druddigon", "locations": ["Ruby Cave (Cave)"], "order": 28 },
  { "name": "Roggenrola", "locations": ["Tanzan Mountain (Cave)"], "order": 29 },
  { "name": "Diglett", "locations": ["Tanzan Mountain (Cave)"], "order": 29 },
  { "name": "Donphan", "locations": ["Tanzan Mountain (Cave)"], "order": 29 },
  { "name": "Lairon", "locations": ["Tanzan Mountain (Cave)"], "order": 29 },
  { "name": "Excadrill", "locations": ["Tanzan Mountain (Cave)"], "order": 29 },
  { "name": "Larvitar", "locations": ["Tanzan Mountain (Depths)"], "order": 30 },
  { "name": "Sneasel", "locations": ["Ametrine Mountain (Cave)"], "order": 30 },
  { "name": "Bergmite", "locations": ["Ametrine Mountain (Cave)"], "order": 30 },
  { "name": "Cubchoo", "locations": ["Ametrine Mountain (Cave)"], "order": 30 },
  
  // --- ORDER 31-40: ROUTE 1 & ADVENTURINE (Late Mid-Game) ---
  { "name": "Tauros", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Miltank", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Bouffalant", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Scyther", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Pinsir", "locations": ["South Adventurine Woods (Land)"], "order": 31 },
  { "name": "Heracross", "locations": ["South Adventurine Woods (Land)"], "order": 31 },
  { "name": "Ponyta", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Doduo", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Tangela", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Deerling", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Emolga", "locations": ["Route 1 (Land)"], "order": 31 },
  { "name": "Zorua", "locations": ["Route 1 (Event) [Hide and Seek]"], "order": 32 },
  { "name": "Bagon", "locations": ["Route 1 (Event) [Puzzle]"], "order": 33 },
  { "name": "Gligar", "locations": ["Route 3 (Land)"], "order": 35 },
  { "name": "Skarmory", "locations": ["Route 3 (Land)"], "order": 35 },
  { "name": "Drampa", "locations": ["Route 1 (Land)"], "order": 36 },
  { "name": "Turtonator", "locations": ["Route 1 (Land)"], "order": 36 },
  
  // --- ORDER 41-50: AMETRINE & ROUTE 2 (Badge 10-12) ---
  { "name": "Swinub", "locations": ["Ametrine City (Land)"], "order": 41 },
  { "name": "Delibird", "locations": ["Ametrine City (Land)"], "order": 41 },
  { "name": "Jynx", "locations": ["Ametrine City (Land)"], "order": 41 },
  { "name": "Lapras", "locations": ["Ametrine City (Surf)"], "order": 41 },
  { "name": "Spheal", "locations": ["Ametrine City (Surf)"], "order": 41 },
  { "name": "Cryogonal", "locations": ["Ametrine Mountain (Cave)"], "order": 42 },
  { "name": "Snorunt", "locations": ["Ametrine Mountain (Cave)"], "order": 42 },
  { "name": "Vanillish", "locations": ["Ametrine Mountain (Cave)"], "order": 42 },
  { "name": "Rotom", "locations": ["Ametrine City (Event)"], "order": 43 },
  { "name": "Honedge", "locations": ["Mirage Tower (Cave)"], "order": 44 },
  { "name": "Golett", "locations": ["Route 3 (Cave)"], "order": 44 },
  { "name": "Absol", "locations": ["Route 4 (Waterfall Event)"], "order": 45 },
  { "name": "Rufflet", "locations": ["Route 4 (Land)"], "order": 45 },
  { "name": "Vullaby", "locations": ["Route 4 (Land)"], "order": 45 },
  { "name": "Bisharp", "locations": ["Route 4 (Land)"], "order": 45 },
  { "name": "Bewear", "locations": ["Route 4 (Land)"], "order": 45 },
  { "name": "Komala", "locations": ["Route 4 (Land)"], "order": 45 },
  { "name": "Hawlucha", "locations": ["Route 2 (Land)"], "order": 46 },
  { "name": "Crustle", "locations": ["Route 2 (Land)"], "order": 46 },
  { "name": "Drapion", "locations": ["Route 2 (Land)"], "order": 46 },
  { "name": "Tyranitar", "locations": ["Route 2 (Land)"], "order": 46 },
  { "name": "Lucario", "locations": ["Route 2 (Land)"], "order": 46 },

  // --- ORDER 51+: END GAME & VICTORY ROAD ---
  { "name": "Drilbur", "locations": ["Tanzan Cove (Cave)"], "order": 51 },
  { "name": "Durant", "locations": ["Tanzan Mountain (Cave)"], "order": 52 },
  { "name": "Heatmor", "locations": ["Pyrous Mountain (Cave)"], "order": 52 },
  { "name": "Deino", "locations": ["Subseven Sanctum (Cave)"], "order": 55 },
  { "name": "Jangmo-o", "locations": ["Teknite Ridge (Land)"], "order": 56 },
  { "name": "Gible", "locations": ["Sugiline Cave (Cave)"], "order": 57 },
  { "name": "Hydreigon", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Volcarona", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Metagross", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Salamence", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Dragonite", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Garchomp", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Goodra", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Kommo-o", "locations": ["Victory Road (Cave)"], "order": 60 },
  { "name": "Dragapult", "locations": ["Victory Road (Cave)"], "order": 60 }
];